"""Pure functions for the standards approval page.

This module provides functions to derive summary counts from rule sets,
build diff models for display, and render the approval page HTML.
These functions are pure (no I/O, no side effects) so they can be
tested independently of the HTTP handler.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from engineering_audit.managed_blocks import (
    get_escaped_opening_marker_pattern_any_id,
    get_escaped_closing_marker_pattern,
)
from engineering_audit.standards import RuleSet, RuleStatus

__all__ = [
    "SummaryCount",
    "DiffModel",
    "derive_summary_counts",
    "build_diff_model",
    "highlight_managed_block_markers",
]


@dataclass(frozen=True)
class SummaryCount:
    """Counts derived from a rule set for the approval summary.

    Attributes:
        new_rules: Count of provisional (ungrill) rules.
        upgraded_to_verified: Count of verified-pass and verified-finding rules.
        findings_recorded: Count of verified-finding rules (broken rules found).
        not_applicable: Count of verified-not-applicable rules (deferred domains).
    """

    new_rules: int
    upgraded_to_verified: int
    findings_recorded: int
    not_applicable: int


@dataclass(frozen=True)
class DiffModel:
    """A diff model for displaying changes to a standards document.

    Attributes:
        document_id: Identifier for the document ('agent-standard', 'human-standard', 'engineering-policy').
        file_exists: True if the current file exists on disk, False if this is a new file.
        current_content: Current file content from disk, or None if file does not exist.
        proposed_content: Proposed content to write (with managed-block markers).
    """

    document_id: str
    file_exists: bool
    current_content: str | None
    proposed_content: str


def derive_summary_counts(rule_set: RuleSet) -> SummaryCount:
    """Derive summary counts from a rule set.

    Returns a dataclass with counts of:
    - new_rules: Provisional (ungrill) rules
    - upgraded_to_verified: Verified-pass and verified-finding rules
    - findings_recorded: Verified-finding rules (found problems)
    - not_applicable: Verified-not-applicable rules (deferred domains)

    Args:
        rule_set: The rule set to analyze.

    Returns:
        A SummaryCount dataclass with the counts.
    """
    new_rules = 0
    upgraded_to_verified = 0
    findings_recorded = 0
    not_applicable = 0

    for rule in rule_set.rules:
        if rule.status == RuleStatus.PROVISIONAL.value:
            new_rules += 1
        elif rule.status == RuleStatus.VERIFIED_PASS.value:
            upgraded_to_verified += 1
        elif rule.status == RuleStatus.VERIFIED_FINDING.value:
            findings_recorded += 1
        elif rule.status == RuleStatus.VERIFIED_NOT_APPLICABLE.value:
            not_applicable += 1

    return SummaryCount(
        new_rules=new_rules,
        upgraded_to_verified=upgraded_to_verified,
        findings_recorded=findings_recorded,
        not_applicable=not_applicable,
    )


def build_diff_model(
    current_content: str | None,
    proposed_content: str,
    document_id: str,
) -> DiffModel:
    """Build a diff model for a standards document.

    Args:
        current_content: Current file content from disk, or None if file doesn't exist.
        proposed_content: Proposed content to write (should include managed-block markers).
        document_id: Document identifier ('agent-standard', 'human-standard', 'engineering-policy').

    Returns:
        A DiffModel ready for rendering.
    """
    return DiffModel(
        document_id=document_id,
        file_exists=current_content is not None,
        current_content=current_content,
        proposed_content=proposed_content,
    )


def highlight_managed_block_markers(content: str) -> str:
    """Highlight managed-block marker lines in HTML-escaped content.

    Takes content that is already HTML-escaped and wraps lines containing
    managed-block markers (opening and closing) in a highlight span.
    Escaping must happen BEFORE this function is called, so content can
    never inject markup and the span itself is never escaped away.

    This is the server-side replacement for client-side marker highlighting
    that was broken in the template's JavaScript.

    Args:
        content: HTML-escaped content that may contain managed-block markers.

    Returns:
        Content with marker lines wrapped in <span class="managed-block-marker">…</span>.
    """
    # Derive patterns from managed_blocks module to ensure consistency.
    # Patterns match escaped HTML markers generated by managed_blocks.py.
    opening_pattern = get_escaped_opening_marker_pattern_any_id()
    closing_pattern = get_escaped_closing_marker_pattern()

    lines = content.split("\n")
    result_lines = []

    for line in lines:
        # Check if this line contains an opening marker
        if re.search(opening_pattern, line):
            result_lines.append(f'<span class="managed-block-marker">{line}</span>')
        # Check if this line contains a closing marker
        elif re.search(closing_pattern, line):
            result_lines.append(f'<span class="managed-block-marker">{line}</span>')
        else:
            result_lines.append(line)

    return "\n".join(result_lines)
